{% set name = "f2" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ayoisaiah/f2/archive/v{{ version }}.tar.gz
  sha256: 44281ba6282fb80868ee4280b6722baaa111b7aeddc1d1c16a8b31df6c0971e5

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - f2 &  # [not win]
    - exe_pid=$!  # [not win]
    - trap "kill -SIGTERM ${exe_pid}" SIGTERM  # [not win]
    - start /b f2   # [win]
    - if %errorlevel% neq 0 exit %errorlevel%  # [win]
    - taskkill /F /im f2.exe  # [win]
    - if %errorlevel% neq 0 exit %errorlevel%  # [win]

about:
  home: https://github.com/ayoisaiah/f2
  license: MIT
  license_file:
    - LICENCE
    - license-files/
  summary: Command-line batch renaming tool
  dev_url: https://github.com/ayoisaiah/f2

extra:
  recipe-maintainers:
    - danielnachun
