{% set name = "f2" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ayoisaiah/f2/archive/v{{ version }}.tar.gz
  sha256: 9fc1868faeb5ee4197d2cf382773e77477014cecd793d96948ef870724c85b9d

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - f2 --help

about:
  home: https://github.com/ayoisaiah/f2
  license: MIT
  license_file:
    - LICENCE
    - license-files/
  summary: Command-line batch renaming tool
  dev_url: https://github.com/ayoisaiah/f2

extra:
  recipe-maintainers:
    - danielnachun
